name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  http: ^1.2.1
  syncfusion_flutter_pdfviewer: ^25.1.41

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  branding: assets/splash/rivalearn_branding.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    branding: assets/splash/rivalearn_branding.png

flutter:
  uses-material-design: true
